django_movie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from rest_framework.authtoken.views import obtain_auth_token


urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("movies.urls")),
    path('', include('django.contrib.auth.urls')),
    path('auth/', obtain_auth_token)
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

movies/urls.py
from django.urls import path, include
from rest_framework.urlpatterns import format_suffix_patterns
from . import views
from . import api
from rest_framework.routers import DefaultRouter

router = DefaultRouter()
router.register('users', views.UserViewSet)

urlpatterns = [
    # for the frontend
    path('', views.index, name='home'),
    path("movie/", views.MoviesView.as_view(), name="movie_list"),
    path("movie/<slug:slug>/", views.MovieDetail.as_view(), name="movie_detail"),
    path("movie/create", views.MovieCreate.as_view(), name="movie_create"),
    path("movie/<slug:slug>/update", views.MovieUpdate.as_view(), name="movie_edit"),
    # my api frame work
    path('api/', include(router.urls)),
    path('api/film', api.film_list),  # list films and create film
    path('api/film/<slug:slug>/', api.film_detail),  # update, delete film
    path('api/category/', api.category_list),
    path('api/category/<slug:slug>', api.category_detail),
    path('api/actor/', api.actor_list),
    path('api/actor/<int:pk>', api.actor_detail),
    path('api/genre/', api.genre_list),
    path('api/genre/<int:pk>', api.genre_detail),
]

movies/models.py
from django.db import models
from datetime import date
from django.urls import reverse


class Category(models.Model):
    """Категории"""
    name = models.CharField("Категория", max_length=150)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class Actor(models.Model):
    """Актеры и режиссеры"""
    name = models.CharField("Имя", max_length=100)
    age = models.PositiveSmallIntegerField("Возраст", default=0)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="actors/")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('actor_detail', kwargs={"slug": self.name})

    class Meta:
        verbose_name = "Актеры и режиссеры"
        verbose_name_plural = "Актеры и режиссеры"


class Genre(models.Model):
    """Жанры"""
    name = models.CharField("Имя", max_length=100)
    description = models.TextField("Описание")
    url = models.SlugField(max_length=160, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Жанр"
        verbose_name_plural = "Жанры"


class Movie(models.Model):
    """Фильм"""
    title = models.CharField("Название", max_length=100)
    tagline = models.CharField("Слоган", max_length=100, default='')
    description = models.TextField("Описание")
    poster = models.ImageField("Постер", upload_to="movies/")
    year = models.PositiveSmallIntegerField("Дата выхода", default=2019)
    country = models.CharField("Страна", max_length=30)
    directors = models.ManyToManyField(Actor, verbose_name="режиссер", related_name="film_director")
    actors = models.ManyToManyField(Actor, verbose_name="актеры", related_name="film_actor")
    genres = models.ManyToManyField(Genre, verbose_name="жанры")
    world_premiere = models.DateField("Примьера в мире", default=date.today)
    budget = models.PositiveIntegerField("Бюджет", default=0,
                                         help_text="указывать сумму в долларах")
    fees_in_usa = models.PositiveIntegerField(
        "Сборы в США", default=0, help_text="указывать сумму в долларах"
    )
    fess_in_world = models.PositiveIntegerField(
        "Сборы в мире", default=0, help_text="указывать сумму в долларах"
    )
    category = models.ForeignKey(
        Category, verbose_name="Категория", on_delete=models.SET_NULL, null=True
    )
    url = models.SlugField(max_length=130, unique=True)
    draft = models.BooleanField("Черновик", default=False)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Фильм"
        verbose_name_plural = "Фильмы"

    def get_absolute_url(self):  # Тут мы создали новый метод
        return reverse('movie_detail', args=[str(self.url)])


class MovieShots(models.Model):
    """Кадры из фильма"""
    title = models.CharField("Заголовок", max_length=100)
    description = models.TextField("Описание")
    image = models.ImageField("Изображение", upload_to="movie_shots/")
    movie = models.ForeignKey(Movie, verbose_name="Фильм", on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Кадр из фильма"
        verbose_name_plural = "Кадры из фильма"


class RatingStar(models.Model):
    """Звезда рейтинга"""
    value = models.SmallIntegerField("Значение", default=0)

    def __str__(self):
        return f'{self.value}'

    class Meta:
        verbose_name = "Звезда рейтинга"
        verbose_name_plural = "Звезды рейтинга"
        ordering = ["-value"]


class Rating(models.Model):
    """Рейтинг"""
    ip = models.CharField("IP адрес", max_length=15)
    star = models.ForeignKey(RatingStar, on_delete=models.CASCADE, verbose_name="звезда")
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="фильм", related_name="ratings")

    def __str__(self):
        return f"{self.star} - {self.movie}"

    class Meta:
        verbose_name = "Рейтинг"
        verbose_name_plural = "Рейтинги"


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    name = models.CharField("Имя", max_length=100)
    text = models.TextField("Сообщение", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    movie = models.ForeignKey(Movie, verbose_name="фильм", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.name} - {self.movie}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = "Отзывы"

movies/forms.py
from django import forms

from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = '__all__'

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, UpdateView, CreateView
from .models import Movie
from .serializers import UserSerializer
from rest_framework import viewsets
from django.contrib.auth.models import User


class UserViewSet(viewsets.ModelViewSet):
    queryset = User.objects.all()
    serializer_class = UserSerializer


def index(request):
    return render(request, 'home.html')


class MoviesView(ListView):
    model = Movie
    queryset = Movie.objects.filter(draft=False)
    template_name = "movies/movie_list.html"


class MovieDetail(DetailView):
    model = Movie
    slug_field = "url"
    template_name = "movies/movie_detail.html"


class MovieUpdate(UpdateView):
    model = Movie
    slug_field = "url"
    fields = '__all__'
    template_name = "movies/movie_edit.html"


class MovieCreate(CreateView):
    model = Movie
    slug_field = "url"
    fields = '__all__'
    template_name = "movies/movie_create.html"

templates/home.html
{% extends 'base.html' %}
{% block title %}
  Главная
{% endblock %}
{% block content %}
  <div class="about">
    <h1>Вас приветсвует:</h1>
    <h2>Серикбаев Мадияр</h2>
    <p>Кино сайт где можно ознакомиться <br>об фильмах и увидеть трейлеры к ним</p>

  </div>
{% endblock %}

templates/movies/movie_create.html
{% extends 'base.html' %}
{% block title %}
  Создать фильм
{% endblock %}

{% block content %}
    <h1>New film</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock content %}

templates/movies/movie_detail.html
{% extends 'base.html' %}
{% block title %}
  {{ movie.title }}
{% endblock %}

{% block content %}
    <div class="left-ads-display col-lg-8">
        <div class="row">
            <div class="desc1-left col-md-6">
                <img src="{{ movie.poster.url }}" width="325px" height="400px">
            </div>
            <div class="desc1-right col-md-6 pl-lg-4">
                <h3 class="editContent" style="outline: none; cursor: inherit;">
                    {{ movie.title }}
                </h3>
                {% if user.is_authenticated %}
                    <a class="btn btn-default" href="{% url 'movie_edit' slug=movie.url %}"><span class="glyphicon glyphicon-pencil"></span>Edit</a>
                {% endif %}
                <h5 class="editContent"></h5>
                <ul>
                    <li style="list-style: none">
                        <span><b>Год:</b> {{ movie.year }}</span></li>
                    <li style="list-style: none">
                        <span><b>Страна:</b> {{ movie.country }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Слоган:</b> {{ movie.tagline }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Режиссер:</b>
                            {% for director in movie.directors.all %}
                                {{ director.name }}
                            {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none"><span><b>Актеры:</b>
                        {% for actor in movie.actors.all %}
                            {{ actor.name }}
                        {% endfor %}
                    </span>
                    </li>
                    <li style="list-style: none"><span><b>Жанр:</b>
                        {% for genre in movie.genres.all %}
                            {{ genre.name }}
                        {% endfor %}
                        </span>
                    </li>
                    <li style="list-style: none"><span><b>Премьера в мире:</b> {{ movie.world_premiere }}</span>
                    </li>
                    <li style="list-style: none">
                        <span><b>Бюджет:</b> ${{ movie.budget }}</span></li>
                    <li style="list-style: none">
                        <span><b>Сборы в США:</b> ${{ movie.fees_in_usa }}</span></li>
                    <li style="list-style: none"><span><b>Сборы в мире:</b> ${{ movie.fess_in_world }}</span>
                    </li>
                    <li style="list-style: none">
                        <a href="#"><b>Рейтинг:</b>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="fa fa-star" aria-hidden="true"
                                  style="outline: none; cursor: inherit;"></span>
                            <span class="editContent"
                                  style="outline: none; cursor: inherit;">5.0</span>
                        </a>
                    </li>
                    <div class="share-desc">
                        <div class="share">
                            <h4 class="editContent"
                                style="outline: none; cursor: inherit;">
                                Share:</h4>
                            <ul class="w3layouts_social_list list-unstyled">
                                <li>
                                    <a href="#" class="w3pvt_facebook editContent"
                                       style="outline: none; cursor: inherit;">
                                    <span class="fa fa-facebook-f"
                                          style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_twitter editContent"
                                       style="outline: none; cursor: inherit;">
                                    <span class="fa fa-twitter"
                                          style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#" class="w3pvt_dribble editContent"
                                       style="outline: none; cursor: inherit;">
                                    <span class="fa fa-dribbble"
                                          style="outline: none; cursor: inherit;"></span>
                                    </a>
                                </li>
                            </ul>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </ul>
            </div>
            <div class="row sub-para-w3layouts mt-5">

            <h3 class="shop-sing editContent">
                О фильме {{ movie.title }}
            </h3>
            <p>
                {% for image in movie.movieshots_set.all %}
                    <img src="{{ image.image.url }}" class="img-movie-shots" width="300px" height="300px" alt="{{ image.description }}">
                {% endfor %}
            </p>
            <p class="editContent" style="outline: none; cursor: inherit;">
                {{ movie.description }}
            </p>
            <p class="mt-3 italic-blue editContent"
               style="outline: none; cursor: inherit;">
                <iframe width="560" height="315"
                        src="https://www.youtube.com/embed/A36LahZNUiE?controls=0"
                        frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                        allowfullscreen>
                </iframe>
            </p>
        </div>
        </div>
      </div>

{% endblock %}

templates/movies/movie_edit.html
{% extends 'base.html' %}
{% block title %}
  Edit film
{% endblock %}

{% block content %}
    <h1>New Movie</h1>
    <hr>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

templates/movies/movie_list.html
{% extends 'base.html' %}

{% block title %}
  Фильмы
{% endblock %}

{% block content %}
    {% for movie in movie_list %}
        <div class="col-md-4 product-men">
            <div class="product-shoe-info editContent text-center mt-lg-4">
                <div class="men-thumb-item">
                    <img src="{{ movie.poster.url }}" width="300px" height="300px">
                </div>
                <div class="item-info-product">
                    <h4 class="">
                        <a href="{% url 'movie_detail' movie.url %}" class="editContent">
                            {{ movie.title }}
                        </a>
                    </h4>

                    <div class="product_price">
                        <div class="grid-price">
                            <span class="money editContent">{{ movie.tagline }}</span>
                        </div>
                    </div>
                    <ul class="stars">
                        <li><a href="#"><span class="fa fa-star"
                                              aria-hidden="true"></span></a>
                        </li>
                        <li><a href="#"><span class="fa fa-star"
                                              aria-hidden="true"></span></a>
                        </li>
                        <li><a href="#"><span class="fa fa-star-half-o"
                                              aria-hidden="true"></span></a>
                        </li>
                        <li><a href="#"><span class="fa fa-star-half-o"
                                              aria-hidden="true"></span></a>
                        </li>
                        <li><a href="#"><span class="fa fa-star-o"
                                              aria-hidden="true"></span></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

    {% endfor %}
    {% if user.is_authenticated %}
        <a href="{% url 'movie_create' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span> Ещё</a>
    {% endif %}
{% endblock %}